---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: opscode-ubuntu-18.04-chef-14
    driver:
      box: bento/ubuntu-18.04
    provisioner:
      product_name: chef
      product_version: latest

suites:
  - name: default
    run_list:
      - recipe[datadog::default]
      - recipe[datadog::process_datadog]
      - recipe[datadog::postgres_datadog]
      - recipe[datadog::zfs_check]
      - recipe[datadog::elastic_datadog]
      - recipe[datadog::zk_datadog]
      - recipe[datadog::kafka_datadog]
      - recipe[datadog::burrow_datadog]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      datadog:
        datadog_api_key: 'abc'
        process:
          instances:
            - name: 'process'
              search_string: 'process'
              tags:
                - tag-1
        postgres:
          instances:
            - username: 'admin'
              password: 'admin'
              db_name: 'default'
              tags:
                - tag-1
        zfs_free:
          instances:
            - storage_pool: 'storage_pool'
        zfs_used:
          instances:
            - storage_pool: 'storage_pool'
        elastic:
          instances:
            - url: 'http://localhost:9200'
              tags:
                - tag-1
        zk:
          instances:
            - host: 'localhost'
              port: 2181
              cluster_name: 'test'
              tags:
                - tag-1
        kafka:
          instances:
            - host: 'localhost'
              port: 8090
              cluster_name: 'test'
              tags:
                - tag-1
        burrow:
          instances:
            - uri: 'http://localhost:8000'
              cluster_names: 
                - 'test'
              tags:
                - tag-1
